### ISSUE TITLE
Cannot locate the code in the "Run the scripts" section

### ISSUE THREAD

**Issue by Xin-Cheng-Wen** [thunlp/ChatEval#12]
Thank you for your work. However, I find that I cannot locate the code in the "Run the scripts" section. For instance, I am unable to find gpt_35_0301.sh for one-by-one communication. Could you please provide an example and the corresponding code?

**Comment by SU-JIAYUAN** [comment]
Can you please kindly help us regarding this issue?

**Comment by chanchimin** [comment]
I have changed the startup method from using bash scripts to using a configuration file. Please try running the command with the following format instead:
```shell
python llm_eval.py --config agentverse/tasks/llm_eval/config.yaml
```
